# Generated by Django 5.2.2 on 2025-06-05 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_review_unique_together'),
        ('trainingsessions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='trainingsessions.session'),
        ),
    ]
