# Generated by Django 5.2.2 on 2025-06-05 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingsessions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('proposed', 'Предложена'), ('waiting', 'Ожидание'), ('confirmed', 'Подтверждена'), ('completed', 'Завершена'), ('cancelled', 'Отменена')], default='proposed', max_length=20),
        ),
    ]
